version: "3.9"

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - redisnet
    ports:
      - "6379:6379"
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.7.0
    restart: always
    networks:
      - elasticnet
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.7.0
    restart: always
    networks:
      - elasticnet
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

networks:
  redisnet:
  elasticnet:
    driver: bridge

volumes:
  esdata: